import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import clsx from "clsx";
import Navbar from "@/components/navbar/navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const font = localFont({
  src: [
    {
      path: "../public/font/f1_regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/f1_bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={clsx(
            "flex flex-col items-center bg-f1-black text-white",
            font.className
          )}
        >
          <Navbar />
          <div className="w-full max-w-[1280px] px-6 pb-16 pt-24 md:px-8">
            {children}
          </div>
          <Toaster
            position="bottom-right"
            toastOptions={{
              classNames: {
                toast: "bg-f1-black-lighter border-0",
                content: "text-white",
                icon: "text-white",
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
